api_platform:
    title: 'GESTION DU DRIVE'
    description: 'Creation des entites user et fichier'
    version: '1.0.0'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
